In [2]:
!pip list

Package                  Version
------------------------ ----------------
apturl                   0.5.2
asttokens                2.4.1
bcrypt                   3.2.0
blinker                  1.4
Brlapi                   0.8.3
certifi                  2020.6.20
chardet                  4.0.0
click                    8.0.3
colorama                 0.4.4
comm                     0.2.2
contourpy                1.3.1
cryptography             3.4.8
cupshelpers              1.0
cycler                   0.12.1
dbus-python              1.2.18
debugpy                  1.8.8
decorator                5.1.1
defer                    1.0.6
distlib                  0.3.9
distro                   1.7.0
distro-info              1.1+ubuntu0.2
dnspython                2.1.0
duplicity                0.8.21
exceptiongroup           1.2.2
executing                2.1.0
fasteners                0.14.1
filelock                 3.16.1
fonttools                4.55.0
fsspec                   2024.10.0
future  

### Tensorflow Installation 

In [4]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
  Using cached tensorflow-2.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (615.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.7/319.7 KB 226.7 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 KB 314.6 kB/s eta 0:00:00a 0:00:01
  Using cached termcolor-2.5.0-py3-none-any.whl (7.8 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached grpcio-1.68.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.2 MB/s eta 0:00:00a 0:00:01
  Using cached tensorflow_io_gcs_filesystem-0.37.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
  Using cached numpy-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.5 MB)
  Using cach

In [1]:
!pip list

Package                      Version
---------------------------- ----------------
absl-py                      2.1.0
apturl                       0.5.2
asttokens                    2.4.1
astunparse                   1.6.3
bcrypt                       3.2.0
blinker                      1.4
Brlapi                       0.8.3
certifi                      2020.6.20
chardet                      4.0.0
click                        8.0.3
colorama                     0.4.4
comm                         0.2.2
contourpy                    1.3.1
cryptography                 3.4.8
cupshelpers                  1.0
cycler                       0.12.1
dbus-python                  1.2.18
debugpy                      1.8.8
decorator                    5.1.1
defer                        1.0.6
distlib                      0.3.9
distro                       1.7.0
distro-info                  1.1+ubuntu0.2
dnspython                    2.1.0
duplicity                    0.8.21
exceptiongroup               1.

In [6]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [ ]:
import tensorflow as tf

node1= tf.constant(3, dtype=tf.int32)
node2= tf.constant(5, dtype=tf.int32)
node3= tf.add(node1, node2)

# create tensorflow session object
sess = tf.compat.v1.Session()
 
# evaluating node3 and printing the result
print("sum of node1 and node2 is :",sess.run(node3))
# closing the session
sess.close()

2024-11-28 12:16:52.319246: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1732776412.341359   11375 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1732776412.348042   11375 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-28 12:16:52.368847: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-28 12:16:55.436519: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL

RuntimeError: The Session graph is empty. Add operations to the graph before calling run().

**<span style="color:red"> Tensorflow as removed session from version 2, We can directly call node3.numpy() to get the result as a NumPy array and print it.</span>**

In [ ]:
import tensorflow as tf

#! Define the constants
node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)

#! Perform element-wise addition
node3 = tf.add(node1, node2)

#! Print the result without needing a session
print("sum of node1 and node2 is:", node3.numpy())
print(node3)

sum of node1 and node2 is: 8
tf.Tensor(8, shape=(), dtype=int32)


**<span style="color:red">In TensorFlow 2.x, the concept of placeholders has been simplified. You no longer need to explicitly define placeholders to feed data into your model.
Instead, you can directly pass data to your model during training or inference.
</span>**

In [5]:
import tensorflow as tf

# Define placeholders for input data
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

# Define an operation (addition)
c = a + b

# Create a session
sess = tf.Session()

# Feed values to the placeholders and run the session
result = sess.run(c, feed_dict={a: 3, b: 4})

print(result)  # Output: 7

AttributeError: module 'tensorflow' has no attribute 'placeholder'

#### <span style="color: rgb(45, 255, 3)"> **Initialisation**</span>

In [29]:
tensor= tf.constant(10)
tensor1=tf.ones((2,3),dtype=tf.int32)
tensor2=tf.zeros((2,3),dtype=tf.int32)
tensor3=tf.eye(3,dtype=tf.int32)
tensor4= tf.random.normal((3,3),mean=0,stddev=1)
tensor5=tf.random.uniform((3,3),minval=0,maxval=1)
tensor6=tf.range(1,10,1.5)
tensor7=tf.cast(tensor,tf.float64,)
print(tensor)
print("-"*100)
print(tensor1)
print("-"*100)
print(tensor2)
print("-"*100)
print(tensor3, "Identity matrix")
print("-"*100)
print(tensor4)
print("-"*100)
print(tensor5)
print("-"*100)
print(tensor6)
print("-"*100)
print(tensor7)
print("-"*100)
print(node2)

tf.Tensor(10, shape=(), dtype=int32)
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32) Identity matrix
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[ 0.3545032   0.13433021  1.6527909 ]
 [-1.0687613  -0.8316954   1.2551463 ]
 [-0.61527175  0.14591677 -1.1046696 ]], shape=(3, 3), dtype=float32)
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[0.20214272 0.33666325 0.7415954 ]
 [0.38124526 0.37298858 0.26063752]
 [0.72620237 0.01

<span style="color: rgb(45, 255, 3)"><big>**Mathematical operations**</big></span>

In [42]:
import tensorflow as tf

x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

# z= tf.add(x,y)
z= x+y
a=y-x #! or tf.subtract(x-y)
b=x/y #! or tf.divide(x,y)
c=x*y#! or tf.multiply(x,y)
d=tf.tensordot(x,y,axes=1) #! Muktipying element and adding all
e=tf.reduce_sum(x*y,axis=0)
x=x**3

print(z)
print("-"*100)
print(z.numpy())
print("-"*100)
print(a.numpy())
print("-"*100)
print(b)
print("-"*100)
print(c)
print("-"*100)
print(d)
print("-"*100)
print(e)
print("-"*100)
print(x)
print("-"*100)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
----------------------------------------------------------------------------------------------------
[10 10 10]
----------------------------------------------------------------------------------------------------
[8 6 4]
----------------------------------------------------------------------------------------------------
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
----------------------------------------------------------------------------------------------------
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
----------------------------------------------------------------------------------------------------
tf.Tensor(46, shape=(), dtype=int32)
----------------------------------------------------------------------------------------------------
tf.Tensor(46, shape=(), dtype=int32)
----------------------------------------------------------------------------------------------------
tf.Tensor([ 1  8 27], shape=(3,),

<span style="color: rgb(45, 255, 3)"><big>Matrix Multiplication</big></span>

In [43]:
x= tf.random.normal((2,3))
y= tf.random.normal((3,4))
z=tf.matmul(x,y)
print(z)
z=x@y
print(z)

tf.Tensor(
[[ 0.40527025 -0.07388318 -1.1959332  -0.16655868]
 [-0.28554678  0.5931215   0.16788556  1.2962734 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.40527025 -0.07388318 -1.1959332  -0.16655868]
 [-0.28554678  0.5931215   0.16788556  1.2962734 ]], shape=(2, 4), dtype=float32)


<span><big> **Indexing**</big></span>

In [51]:
x=tf.random.normal((10,))
print(x)
print("-"*100)
print(x[:])
print("-"*100)
print(x[1:3])
print("-"*100)
print(x[::2])
print("-"*100)
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)
print(x_ind)


tf.Tensor(
[ 0.50331616  0.33214182  0.36347142 -0.44455165 -0.5522923  -1.0944899
  0.2486316   0.27290583 -0.5109242  -1.5624675 ], shape=(10,), dtype=float32)
----------------------------------------------------------------------------------------------------
tf.Tensor(
[ 0.50331616  0.33214182  0.36347142 -0.44455165 -0.5522923  -1.0944899
  0.2486316   0.27290583 -0.5109242  -1.5624675 ], shape=(10,), dtype=float32)
----------------------------------------------------------------------------------------------------
tf.Tensor([0.33214182 0.36347142], shape=(2,), dtype=float32)
----------------------------------------------------------------------------------------------------
tf.Tensor([ 0.50331616  0.36347142 -0.5522923   0.2486316  -0.5109242 ], shape=(5,), dtype=float32)
----------------------------------------------------------------------------------------------------
tf.Tensor([ 0.50331616 -0.44455165], shape=(2,), dtype=float32)


<span><big>**Reshaping**</big></span>

In [65]:
x=tf.range(9)
print(x)
print("-"*100)
x=tf.reshape(x,(3,3))
print(x)
print("-"*100)
x=tf.transpose(x,[1,0])
print(x)
print("-"*100)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
----------------------------------------------------------------------------------------------------
